drop table Товар

CREATE TABLE Товар (
	КодТовара int GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 1 INCREMENT BY 1),
	Название VARCHAR(50), 
	Цена MONEY,
	Тип VARCHAR(50), 
	Сорт VARCHAR(50), 
	Город VARCHAR(50),
	Остаток INT)