
CREATE TABLE Сделка(
	КодСделки INT GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	КодТовара INT NOT NULL,
	КодКлиента INT NOT NULL,
	Количество INT NOT NULL DEFAULT 0,
	Дата timestamp without time zone NOT NULL default (now() at time zone 'utc'),
	Остаток INT,
	CONSTRAINT fk_Товар FOREIGN KEY(КодТовара) REFERENCES Товар,
	CONSTRAINT fk_Клиент FOREIGN KEY(КодКлиента) REFERENCES Клиент);